Access multiple records with type: 'row'
ray-di/Ray.MediaQuery pull request #31
Opened 2022-05-27 12:30 UTC by pazworld

Add Interface which access multiple records with type: 'row', and test that interface.

2022-05-27 12:59 UTC, koriym requested changes

2022-05-27 12:59 UTC, koriym commented on tests/Fake/Queries/TodoListRowInterface.php
> +}
```suggestion
}

```

2022-05-27 13:00 UTC, koriym commented
`composer sa`を実行して確認してください。

2022-05-30 04:57 UTC, closed without merging

2022-05-30 04:59 UTC, pazworld commented
この件は「type: rowでアクセスすると1行のみ返ってくるはず」という勘違いによるものでした。クローズします。お騒がせしました。