Extract MediaQueryModule
ray-di/Ray.MediaQuery pull request #36
Opened 2022-06-12 05:58 UTC by koriym

… and MediaQueryBaseModule

2022-06-16 09:14 UTC, NaokiTsuchiya requested changes

2022-06-16 09:14 UTC, NaokiTsuchiya commented on README.ja.md
> +use Ray\AuraSqlModule\AuraSqlModule;use Ray\MediaQuery\ApiDomainModule;use Ray\MediaQuery\DbQuery\DbQueryConfig;use Ray\MediaQuery\DbQuery\Queries;use Ray\MediaQuery\MediaQueryModule;use Ray\MediaQue
```suggestion
use Ray\AuraSqlModule\AuraSqlModule;
use Ray\MediaQuery\ApiDomainModule;
use Ray\MediaQuery\DbQuery\DbQueryConfig;
use Ray\MediaQuery\DbQuery\Queries;
use Ray\MediaQuery\MediaQueryModule;
use Ray\MediaQuery\WebQuery\WebQueryConfig;
```

2022-06-16 09:14 UTC, NaokiTsuchiya commented on README.md
> +use Ray\AuraSqlModule\AuraSqlModule;use Ray\MediaQuery\ApiDomainModule;use Ray\MediaQuery\DbQuery\DbQueryConfig;use Ray\MediaQuery\DbQuery\Queries;use Ray\MediaQuery\MediaQueryModule;use Ray\MediaQue
```suggestion
use Ray\AuraSqlModule\AuraSqlModule;
use Ray\MediaQuery\ApiDomainModule;
use Ray\MediaQuery\DbQuery\DbQueryConfig;
use Ray\MediaQuery\DbQuery\Queries;
use Ray\MediaQuery\MediaQueryModule;
use Ray\MediaQuery\WebQuery\WebQueryConfig;
```

2022-06-16 09:38 UTC, koriym commented
@NaokiTsuchiya 1.0以前とはいえ、DbQueryやPagesIntetfaceのBCブレイクが痛いですね。

2022-06-16 09:46 UTC, NaokiTsuchiya approved these changes

2022-06-16 09:48 UTC, NaokiTsuchiya commented
> @NaokiTsuchiya 1.0以前とはいえ、DbQueryやPagesIntetfaceのBCブレイクが痛いですね。

そうですね😢

最低限rectorルールも用意しておくとかした方が良いかもでしょうか。。。

2022-06-16 15:41 UTC, koriym commented
@NaokiTsuchiya namespaceを分けるのをやめ（諦め？）、２つのモジュールに分けてそれぞれinstallするという構造だけを残しました。

2022-06-17 03:22 UTC, NaokiTsuchiya approved these changes

2022-06-17 03:36 UTC, merged